// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.Infrastructure;

#nullable disable

namespace UserService.Infrastructure.Migrations
{
    [DbContext(typeof(UserServiceDbContext))]
    [Migration("20250708061331_UserCreated")]
    partial class UserCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Amreli, India",
                            CreatedAt = new DateTime(2025, 7, 8, 11, 43, 31, 430, DateTimeKind.Local).AddTicks(9853),
                            Email = "dhruvilchotaliya@gmail.com",
                            FirstName = "Dhruvil",
                            LastName = "Chotaliya",
                            Password = "Dhruvil@123",
                            PhoneNumber = "1234567890",
                            PinCode = "365601"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ahmedabad, India",
                            CreatedAt = new DateTime(2025, 7, 8, 11, 43, 31, 430, DateTimeKind.Local).AddTicks(9855),
                            Email = "shrutibhalodia@gmail.com",
                            FirstName = "Shruti",
                            LastName = "Bhalodia",
                            Password = "Shruti@123",
                            PhoneNumber = "1234567890",
                            PinCode = "380001"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ahmedabad, India",
                            CreatedAt = new DateTime(2025, 7, 8, 11, 43, 31, 430, DateTimeKind.Local).AddTicks(9858),
                            Email = "richakamani@gmail.com",
                            FirstName = "Richa",
                            LastName = "Kamani",
                            Password = "Richa@123",
                            PhoneNumber = "1234567890",
                            PinCode = "380001"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
